version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: "post@gres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"